FROM python:3.11-slim

ENV PIP_DISABLE_PIP_VERSION_CHECK=1
ENV PYTHONUNBUFFERED=1

WORKDIR /app

# Copiar requirements.txt
COPY requirements.txt .

# Crear un entorno virtual
RUN python -m venv /venv

# Instalar dependencias en el entorno virtual
RUN /venv/bin/pip install --no-cache-dir -r requirements.txt

# Copiar el código de la aplicación
COPY . .

# Exponer el puerto (opcional, depende de tu app)
EXPOSE 8000

# Usar el entorno virtual para ejecutar la aplicación
CMD ["/venv/bin/uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]
